#!/usr/bin/env bash

set -xeu -o pipefail

# The absolute path to the directory of this script.
BRAGGHLS_DIR="$( cd "$(dirname "$0")" ; pwd -P)/../.."
C_COMPILER=$(which clang)
CXX_COMPILER=$(which clang++)
echo $BRAGGHLS_DIR

/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-op-defs -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/HLS.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/HLS.inc.cpp
/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-op-decls -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/HLS.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/HLS.inc.h
/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-dialect-defs -dialect=hls -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/HLS.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/HLSDialect.inc.cpp
/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-dialect-decls -dialect=hls -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/HLS.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/HLSDialect.inc.h
/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-typedef-defs -typedefs-dialect=hls -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/HLS.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/HLSTypes.inc.cpp
/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-typedef-decls -typedefs-dialect=hls -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/HLS.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/HLSTypes.inc.h
/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-enum-defs -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/HLS.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/HLSEnums.inc.cpp
/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-enum-decls -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/HLS.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/HLSEnums.inc.h
/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-attrdef-defs -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/HLS.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/HLSAttributes.inc.cpp
/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-attrdef-decls -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/HLS.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/HLSAttributes.inc.h
/Users/mlevental/dev_projects/scalehls/build/bin/mlir-tblgen -gen-pass-decls -I /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/llvm/include -I/Users/mlevental/dev_projects/scalehls/build/include -I/Users/mlevental/dev_projects/scalehls/polygeist/llvm-project/mlir/include -I/Users/mlevental/dev_projects/scalehls/build/tools/mlir/include -I/Users/mlevental/dev_projects/bragghls/include -I/Users/mlevental/dev_projects/bragghls/cmake-build-debug/include /Users/mlevental/dev_projects/bragghls/bragghls_opt/HLS/Passes.td --write-if-changed -o $BRAGGHLS_DIR/bragghls_opt/HLS/Passes.inc.h
